export const FORM_SET_DOG_ID = 'FORM_SET_DOG_ID'
export const FORM_SET_DOG_SHOW_ID = 'FORM_SET_DOG_SHOW_ID'
export const FORM_SET_JUDGE_ID = 'FORM_SET_JUDGE_ID'
export const FORM_SET_DOG_CLASS = 'FORM_SET_DOG_CLASS'
export const FORM_SET_ROUND = 'FORM_SET_ROUND'
export const FORM_SET_CATEGORY = 'FORM_SET_CATEGORY'
export const FORM_SET_RANK = 'FORM_SET_RANK'
export const FORM_SET_SCORE = 'FORM_SET_SCORE'
export const FORM_SET_NOTE = 'FORM_SET_NOTE'
export const FORM_CLEAR = 'FORM_CLEAR'
// To use for attribute setting actions
export const formSetters = {
  dogId: FORM_SET_DOG_ID,
  dogShowId: FORM_SET_DOG_SHOW_ID,
  judgeId: FORM_SET_JUDGE_ID,
  dogClass: FORM_SET_DOG_CLASS,
  round: FORM_SET_ROUND,
  category: FORM_SET_CATEGORY,
  rank: FORM_SET_RANK,
  score: FORM_SET_SCORE,
  note: FORM_SET_NOTE
}


export const FORM_FETCH_DOG_OPTIONS_REQUEST = 'FORM_FETCH_DOG_OPTIONS_REQUEST'
export const FORM_FETCH_DOG_OPTIONS_SUCCESS = 'FORM_FETCH_DOG_OPTIONS_SUCCESS'
export const FORM_FETCH_DOG_OPTIONS_FAILURE = 'FORM_FETCH_DOG_OPTIONS_FAILURE'
export const FORM_FETCH_JUDGE_OPTIONS_REQUEST = 'FORM_FETCH_JUDGE_OPTIONS_REQUEST'
export const FORM_FETCH_JUDGE_OPTIONS_SUCCESS = 'FORM_FETCH_JUDGE_OPTIONS_SUCCESS'
export const FORM_FETCH_JUDGE_OPTIONS_FAILURE = 'FORM_FETCH_JUDGE_OPTIONS_FAILURE'
export const SAVE_ACHIEVEMENT_REQUEST = 'SAVE_ACHIEVEMENT_REQUEST'
export const SAVE_ACHIEVEMENT_SUCCESS = 'SAVE_ACHIEVEMENT_SUCCESS'
export const SAVE_ACHIEVEMENT_FAILURE = 'SAVE_ACHIEVEMENT_FAILURE'


export const ADD_DOG_ENTITY = 'ADD_DOG_ENTITY'
export const ADD_DOG_ENTITIES = 'ADD_DOG_ENTITIES'
export const REMOVE_DOG_ENTITY = 'REMOVE_DOG_ENTITY'
export const CLEAR_DOG_ENTITIES = 'CLEAR_DOG_ENTITIES'
export const ADD_JUDGE_ENTITY = 'ADD_JUDGE_ENTITY'
export const ADD_JUDGE_ENTITIES = 'ADD_JUDGE_ENTITIES'
export const REMOVE_JUDGE_ENTITY = 'REMOVE_JUDGE_ENTITY'
export const CLEAR_JUDGE_ENTITIES = 'CLEAR_JUDGE_ENTITIES'
export const ADD_ACHIEVEMENT_ENTITY = 'ADD_ACHIEVEMENT_ENTITY'
export const ADD_ACHIEVEMENT_ENTITIES = 'ADD_ACHIEVEMENT_ENTITIES'
export const REMOVE_ACHIEVEMENT_ENTITY = 'REMOVE_ACHIEVEMENT_ENTITY'
export const CLEAR_ACHIEVEMENT_ENTITIES = 'CLEAR_ACHIEVEMENT_ENTITIES'

